apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: pi-swarm
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v3.1.0
          ports:
            - containerPort: 9090
              name: http
          args:
            - --config.file=/etc/prometheus/prometheus.yml
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
      volumes:
        - name: config
          configMap:
            name: prometheus-config
